# Intro
numpy is the go to library for numerical computation in python*. 
1. Numpy makes dealing with vectors and matrices simple and easy
2. It has all the math functions you can imagine*

## Scipy
this is the reason for all the asterisks. In theory:
1. Numpy - interface for array (and matrix) creation and manipulation
2. Scipy - all the math 

In practice:
1. Numpy is self contained - contains on top of an interface to arrays and matrices most of the "obvious" math functions you may need.
2. Scipy - more inclusive, supposedly more actively updated in terms of math functions

# First you import
import numpy is **always** done as following

In [2]:
# run forest run 
import numpy as np

# Arrays
run the next cell to see how arrays behave

In [3]:
a = np.array([1, 2, 3])
print(a)

b = np.array([[1, 2],
              [3, 4]])
print(b)

[1 2 3]
[[1 2]
 [3 4]]


As you can see you can create arrays by using the array functions on nested lists. Each level of nesting creates another dimension. To see the shape of an array access its shape property `<array>.shape`. To see how many elements are in it access its size property `<array>.size`. Do that for arrays `a` and `b`.

In [34]:
print(a.shape)
print(a.size)
print(b.shape)
print(b.size)

(3,)
3
(2, 2)
4


## Array factory methods
array factory methods are methods used for creating arrays. You've already witnessed the shock and awe of the `array` function. Now try your luck with:
1. the `zeros` function for creating an array of zeros with 3 rows and 5 columns
2. the `ones` function for creating an array of ones with 5 rows and 2 columns with data type uint8
3. the `eye` function for creating a diagonal matrix of size 3
4. the `tril` function for creating a lower triangular matrix from the ones array you previously created
5. the `zeros_like` function for creating an array of zeros the same shape as array `b`

use inline docummentation with shift-tab or your trusty search engine to understand the inner workings of these functions

In [49]:
c = np.zeros((3,5))
print("Now Printing Array C:")
print(c)
d = np.ones((5,2))
print("Now Printing Array D:")
print(d)
e = np.eye(3)
print("Now Printing Array E:")
print(e)
f = np.tril(d)
print("Now Printing Array F:")
print(f)
g = np.zeros_like(b)
print("Now Printing Array G:")
print(g)

Now Printing Array C:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Now Printing Array D:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Now Printing Array E:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Now Printing Array F:
[[1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Now Printing Array G:
[[0 0]
 [0 0]]


### range
to generate a range of integers we can use the numpy counter part of the built-in `range` function `arange`. run the next cell to behold its glory.

In [52]:
v = np.arange(36)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


# Indexing
indexing such complex beasts may look daunting at first but fear not.
## simple indexing
simple indexing and slicing is done the exact same way as you would for a list in good old stock python. Use your knowledge and wits to achieve the following:
1. print the 5'th element of `v`
2. print a slice of v containing elements 2, 5, 8, 11
3. print a slice of v containing elements 5, 4, 3, ...
4. print a slice of v containing elements 32, 33, 34, ...

In [71]:
print(v[4])
print(v[2:14:3])
print(v[5::-1])
print(v[32::1])

4
[ 2  5  8 11]
[5 4 3 2 1 0]
[32 33 34 35]


To practice some more involved indexing we'll need an interesting array. Run the next cell to generate this.

In [64]:
vr = v.reshape((9, -1))  # reshaping to 9 rows and 4 columns. 
                         # using -1 tells numpy to do the math for you. you can only do this for one dimension
print(vr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


## 2D indexing
it may be usful, just for a second, to think of a 2D numpy array as a list of lists. One list for each row.

In [65]:
l_2d = [[1, 2],
        [3, 4]]

to access the first element in second row we can try

In [66]:
l_2d[1][0]  # fetch the second row (list) and then fetch the first element

3

This would also work for array `b`. Try it

In [67]:
b[1][0]

3

Numpy syntax is much nicer. To acces the first element of the second row we can simply use

In [68]:
b[1, 0]   # the element at coordinates (1, 0)

3

Now forget all this list nonsense and print the 3rd element of the 5th row of `vr`

In [70]:
print(vr[4,2])

18


Now achieve some 2D magic
1. print the second column of `vr`
2. print the third row of `vr`
3. print the subarray containing rows 3, 4, 5 and columns 2, 3 or `vr`

In [109]:
print(vr[:,1])
print(vr[2,:])
print(vr[2:5,1:3])

[ 1  5  9 13 17 21 25 29 33]
[ 8  9 10 11]
[[ 9 10]
 [13 14]
 [17 18]]


It's important to note that unlike list slices or numpy arrays are *views* not *copies*. This means that changing elements of a slice effect the original array. 
1. Generate a subarray containing rows 3, 4, 5 and columns 2, 3 or `vr`
2. change the element at coordinates (0, 0) to 99 and print `vr`

In [111]:
new = vr[2:5,1:3]
new[0,0] = 99
print(vr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 99 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


To create a copy, we will use the copy method of the generated slice object. Try the previous routine with a copy (choose a number other than 99).

In [116]:
newcopy = np.copy(vr[2:5,1:3])
newcopy[0,0] = 65
print(vr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 99 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


## Get elements at - fancy indexing
Let's say we'd like the elements at (coordinates) (0, 0), (5, 1), (8, 2) of `vr`. We can achieve this with integer arrays or lists. Behold

In [128]:
print(vr[[0, 5, 8], [0, 1, 2]])

[ 0 21 34]


### Smarty pants
But why can't we just pass a list of coordinates (0, 0), (5, 1), (8, 2)? We can, but it will require some python voodoo. Introducing `zip`, the trusty python zipper. As it name would imply it zips stuff together. Run the following cell to get a taste

In [118]:
given_names = ['John', 'Darth', 'Prince']
surnames = ['Snow', 'Vader', '']

for (name, surname) in zip(given_names, surnames):
    print('Please welcome {}'.format(' '.join([name, surname])))

Please welcome John Snow
Please welcome Darth Vader
Please welcome Prince 


`zip` is great and it can zip together any number of sequences you throw at it. 

In [122]:
given_names = ['John', 'Darth', 'Prince']
surnames = ['Snow', 'Vader', '']
occupations = ['*spoiler*', 'Sith lord', 'Singer']

for (name, surname, occupation) in zip(given_names, surnames, occupations):
    print('Please welcome {} a fantastic {}'.format(' '.join([name, surname]), occupation))

Please welcome John Snow a fantastic *spoiler*
Please welcome Darth Vader a fantastic Sith lord
Please welcome Prince  a fantastic Singer


** side note ** - there are many useful iteration tools in python. Many of them in the itertools library. Try it for yourself: import `product` from the `itertools` library and run the previous cell with `product` instead of `zip`.

Back to our quest - Use the `zip` function, the splat operator and some magic to get the coordinates we want. Define a function to make the following cell do as you want.

In [148]:
elements = vr[[0, 5, 8], [0, 1, 2]]
elements = vr[[0, 5, 8], [0, 1, 2]]
list_of_coords = [[0, 5, 8], [0, 1, 2]]

for (row, column, elem) in zip(list_of_coords[1][:3], list_of_coords[:3][0], elements):
    print('coordinates ({},{}) in array vr is {}'.format(column, row , elem))

# ---

#list_of_coords = [[0, 5, 8], [0, 1, 2]]
#print(vr[coords_to_inds(list_of_coords)])

coordinates (0,0) in array vr is 0
coordinates (5,1) in array vr is 21
coordinates (8,2) in array vr is 34


### combining index types
you can also combine index types: simple, slicing, fancy, by using different index type for each dimension. Try it for yourself and once you understand the trick. Perform the following magical acts on `vr`:
1. print rows 5, 6, ... but with the columns in reverse order
2. print columns 3, 1 with rows 0, 1, .., 4
3. print row 7 with columns 0, 1, 2

In [180]:
print(np.flip(vr,-1)[5:7,:])
print(vr[0:5,1:4:2])
print(vr[7:8,0:3])

[[23 22 21 20]
 [27 26 25 24]]
[[ 1  3]
 [ 5  7]
 [99 11]
 [13 15]
 [17 19]]
[[28 29 30]]


# Functions using arrays
the real power of numpy is that it allows us treat arrays as we would any other number. Run the following cell

In [181]:
print(np.exp(vr))  # exponenting each element in vr
print(vr ** 3)  # raising each element in vr to the third power

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 9.88903032e+42 2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
 [8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09]
 [2.64891221e+10 7.20048993e+10 1.95729609e+11 5.32048241e+11]
 [1.44625706e+12 3.93133430e+12 1.06864746e+13 2.90488497e+13]
 [7.89629602e+13 2.14643580e+14 5.83461743e+14 1.58601345e+15]]
[[     0      1      8     27]
 [    64    125    216    343]
 [   512 970299   1000   1331]
 [  1728   2197   2744   3375]
 [  4096   4913   5832   6859]
 [  8000   9261  10648  12167]
 [ 13824  15625  17576  19683]
 [ 21952  24389  27000  29791]
 [ 32768  35937  39304  42875]]


Numpy also enables treating arrays as numbers with arithmetic operators (+, *, ...) 
1. generate a range 0,..,8 and reshape it as a 3 by 3 matrix
2. generate a matrix of ones with a similar size
3. print the addition of the two matrices
4. print the multiplication of the two
5. increment the range matrix by 2
5. print the division of the one matrix by the range matrix incremented by 1

In [188]:
h = np.arange(9).reshape(3,3)
print(h)
i = np.ones_like(h)
print(i)
j = h+i
print(j)
k = h*i
print(k)
h += 2
print(h)
l = i / (h+1)
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Please note that array multiplication is element-wise thie is very different from matrix multiplication. Use the `dot` function to perform matrix multiplication for the one matrix and the range matrix.

In [190]:
print(np.dot(i,h))

[[15 18 21]
 [15 18 21]
 [15 18 21]]


## Numpy is optimized
numpy array functions are not only easy on the eyes and hands, they are also highly optimized. This means that a numpy function or vectorized function will run much faster than the same computation using loops. 
1. Time the run of the following cell containing vectorized code
2. Generate an element wise version of this code using for loops (you can still use np.exp for each element)
3. Time your code. Do you see any difference?

In [194]:
# run forest run
%timeit np.exp(vr)

The slowest run took 18.17 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.86 µs per loop


In [196]:
%%timeit
for e in vr:
    np.exp(e)

The slowest run took 51.62 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.6 µs per loop


## Numpy arrays are objects
this means that we can call their methods. To reshape `v` we simply called `v.reshape(<new-shape>)` and not `np.reshape(v, <new-shape>)`. 

In [197]:
# run forest run
print(v)
print(np.sum(v))
print(v.sum())

[ 0  1  2  3  4  5  6  7  8 99 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
720
720


## Functions are objects
this is crazy but functions are also objects and also have methods. In particular numpy binary functions have two interesting methods `reduce` and `accumulate`. Run the following cell

In [198]:
# run forest run
u = np.arange(6)
print(u)

print(np.add(u, u+2))
print(np.add.reduce(u))
print(np.add.accumulate(u))

[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
15
[ 0  1  3  6 10 15]
